name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.17.1, 20.x, 22.x]        

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      env:
        NODE_OPTIONS: "-r ./preload.js"
    - run: node index.js
