name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    

    strategy:
      matrix:
        os: [windows-latest] 
        node-version: [18.17.1, 22.x]        

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}        
      env:
        COMSPEC: C:\Windows\system32\cmd.exe
        NODE_OPTIONS: "-r ./preload.js"
    - run: npm install
